spring:
  application:
    name: Config-Default

eureka:
  instance:
    prefer-ip-address: true
    appname: config-server-test
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

user:
  role: Admin

welcome:
  message: Welcome to the Spring Cloud Config managed application!
